language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq fglrx opencl-headers
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.add("FactCheck");'
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/OpenCL`); Pkg.resolve()'
  - julia -e 'using OpenCL; @assert isdefined(:OpenCL); @assert typeof(OpenCL) === Module'
  
  - julia test/test_platform.jl
  - julia test/test_context.jl
  - julia test/test_device.jl
  - julia test/test_buffer.jl
  - julia test/test_cmdqueue.jl
  - julia test/test_event.jl
  - julia test/test_program.jl
  - julia test/test_kernel.jl

  - julia examples/demo.jl
  - julia examples/performance.jl
  - julia examples/hands_on_opencl/ex04/vadd_chain.jl
  - julia examples/hands_on_opencl/ex05/vadd_abc.jl
  - julia examples/hands_on_opencl/ex06/matmul.jl
